version: '3.8'

services:
  nut-shutdown:
    build: .
    container_name: nut-shutdown
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./secrets/id_ed25519:/run/secrets/id_ed25519:ro
      - ./secrets/known_hosts:/run/secrets/known_hosts:ro
    read_only: true
    tmpfs:
      - /tmp
